### ISSUE TITLE
"Three state" values

### ISSUE THREAD

**Issue by ssette** [grijjy/GrijjyFoundation#1]
In some REST API (i.e. Activiti) there are cases in witch  a boolean value is used as a three state value. 
I.e. in Activiti there are some boolean values used as a query criteria with this behavior (i.e the "suspended" parameter) :
- if the value is true then only the suspended process instances are returned
- if the value is false only the not suspended  process instances are returned
- if non value is specified all instances are returned.

This behavior cannot be obtained using a record like this :
MyRecord = record
  suspended: boolean; 
end;

I've solved declaring suspended as string and using the [BsonIgnoreIfDefault] but this not the right way to solve the problem.

There should be a specific type to support this use case (quite frequent). Or, as alternative, add support for the Variant type which can handle null values

**Comment by erikvanbilsen** [comment]
You could define an enum type like:

type
  TTriState = (No, Yes, NotSpecified);

And use that as the type for "suspended".

Or you could define a specific enum type for this particular case:

type
  TSomeEnum = (SuspendedOnly, RunningOnly, All);

**Comment by ssette** [comment]
Hi Erik,

tank you for the answer.
What you suggests works but is problematic because I need to serialize the suspended value as boolean ("suspended":true). This means my enumeration should be TTriState = (False, True, NotSpecified);
This cause a name clash with Boolean True and False and to avoid to serialize "suspended" in the case of "NotSpecified" I need to annotate the declaration with [BsonDefaultValue(NotSpecified)] and this is not supported ([BsonDefaultValue(2)] shold work instead ...)

Or is there a way to customize how the enumeration values are serialized ?

**Comment by neslib** [comment]
Ok, I see your problem.

Regarding the first issue: I am able to use "False" and "True" without name clashing on Delphi 10 Seattle and later. If that doesn't work for you, you could try prefixing them with an ampersand:

`TTriState = (&False, &True, NotSpecified);`

You also may want to set `{$SCOPEDENUMS ON}`

Regarding default values: I updated the library so you can now supply default values for enums, but you **have** to specify the default value as an ordinal, as in `[BsonDefaultValue(2)]`. Please pull the latest version.

You can now serialize like this:

```
type
  TTriState = (False, True, NotSpecified);

type
  TMyRecord = record
  public
    [BsonDefaultValue(2)]
    [BsonIgnoreIfDefault]
    Suspended: TTriState;
  public
    procedure Initialize;
  end;

{ TMyRecord }

procedure TMyRecord.Initialize;
begin
  { Set default value }
  Suspended := TTriState.NotSpecified;
end;

procedure TestSerialization;
var
  RecA, RecB: TMyRecord;
  Json: String;
begin
  { Test serialization }
  RecA.Suspended := TTriState.NotSpecified;
  TgoBsonSerializer.Serialize(RecA, Json);
  TgoBsonSerializer.Deserialize(Json, RecB);
end;
```

Note that enums are serialized using their ordinal value. If you want to serialize them to strings instead, you also need to add the `[BsonRepresentation(TgoBsonRepresentation.String)]` attribute.

**Comment by ssette** [comment]
Tanks a lot Erik !
A question: why not add support for variant ?
In Activiti I have to deal with structures like this one :
{
  "name" : "variableName",
  "value" : "variableValue",
  "scope" : "local",
  "type" : "string"
}

this is exactly a Variant. To handle this structure I've implemented a custom serializer but I think a better solution would be to have direct Variant support.
I've tried to add myself Variant support but the only solution I've found is to extend IgBsonReader/Writer adding two new methods Read/WriteValue .

Tanks again for the really impressive job !

**Comment by neslib** [comment]
Thanks!

I didn't add support for variants, because we never use them and haven't had the need for them yet. The same goes for TValue, which is another form of variant.

You are probably right that you need to extend the reader/writer classes to support this. Feel free to add variant support yourself if you want to. If you want to share it, you can create a pull request.

But I think using a custom serializer for you variant needs may be a good solution as well...
