### ISSUE TITLE
Request to make Host/Port properties as writable in TgoSocketConnection

### ISSUE THREAD

**Issue by evgeny-k** [grijjy/GrijjyFoundation#16]
Pls make Host/Port properties as writable in TgoSocketConnection.

by other hand, you can create a new public method
```
    function Connect(const AHostname: String;
      const APort: Word; const AUseNagle: Boolean = False): Boolean;
```
that will call private `PostConnect` method internally.

**Comment by allendrennan** [comment]
Added in [5b99bff](https://github.com/grijjy/GrijjyFoundation/commit/5b99bffcbfb2520c53b0afa4cf9560effdae782c)
