### ISSUE TITLE
Add release / version tag

### ISSUE THREAD

**Issue by Pawe1** [grijjy/GrijjyFoundation#3]
Hello

I got a bit bored and I consider adding Your ZeroMQ wrapper as another Delphinus package but...

...to add "Grijjy foundation" as a dependency it have to contain at least one revision marked as "release" (https://github.com/grijjy/GrijjyFoundation/releases) :stuck_out_tongue: 

It's not any crucial issue but could You guys add some tag / tags for current / future releases in this repository?
[Thanks!]

Regards
P.

**Comment by allendrennan** [comment]
I went ahead and tagged some of the repositories as release.  Let me know if you need anything else.

Regards,  Allen

**Comment by Pawe1** [comment]
Uhm... I meant some number like `0.0.1` / `1.0.0` / `v0.0.1` / `v1.0.0`  / `1.0.0-alpha` / `1.0.0-beta` / `v0.0.1-beta` / `...` that meets [semantic versioning template](http://semver.org). :stuck_out_tongue: 
Sorry if I wasn't clear...

[Oh... I found that there is also some embeded wizard on GitHub](https://developer.github.com/v3/repos/releases/#create-a-release)

Also GitHub treats differently release tags with numbers and displays it in other way
Compare
https://github.com/grijjy/GrijjyFoundation/releases
with
https://github.com/gabr42/OmniThreadLibrary/releases
https://github.com/synopse/mORMot/releases

**Comment by Pawe1** [comment]
<bump>

Maybe just replace tag named **release** with 1.0.0 and that's all :wink:

[Thanks!]

**Comment by Pawe1** [comment]
Oh... I have found that there are some more clicks needed to make tag to be seen as a release by GitHub...

0. Rename tag somehow using number (& push it to GitHub remote ofc)

1. 
![1](https://user-images.githubusercontent.com/22169532/31327692-26e35cbe-acd1-11e7-9799-c4396d2c65c1.png)

2. 
![2](https://user-images.githubusercontent.com/22169532/31327702-2febeb50-acd1-11e7-804c-0c35e892a97b.png)

3.
![3](https://user-images.githubusercontent.com/22169532/31327710-3983dd30-acd1-11e7-9533-36c396e122b3.png)
You probably have to write anything (like re-typing version number)

Sorry for being inaccurate...

**Comment by erikvanbilsen** [comment]
I followed your steps. Let me know if this works.

**Comment by Pawe1** [comment]
@erikvanbilsen It's ok now.
You can also do the same thing inside GrijjyCloudLogger and DelphiZeroMQ repositories :wink: (same problem)
 Thanks!
