### ISSUE TITLE
TgoBsonSerializer can not serialize tkmrecord type records

### ISSUE THREAD

**Issue by dkounal** [grijjy/GrijjyFoundation#36]
I noticed that I get an error that serializer can serialize only class and records,.
The problem is found in Grijjy.Bson.Serialization file and it is caused by the ATypeInfo.Kind that returns the record I am using as tkmrecord. 
This record is show as tkmrecord because I am using a "class operator Initialize(out rec: Depvis);". I remove it, it is again a tkrecord.
I add tkmrecord in every "case of" that tkrecord existed, and it works. Is this a problem?

**Comment by neslib** [comment]
Don't know yet if this is a problem. There may be a problem with the Initialize/Finalize/Assign operators not being called at the appropriate times when (de)serializing. This may require some special code.
I will look into this and get back to you...

**Comment by erikvanbilsen** [comment]
There was indeed an issue with the Initialize operator not being called when deserializing. That should be fixed now, and the serializer officially supports Custom Managed Records now.
