### ISSUE TITLE
TDateTime Serialization

### ISSUE THREAD

**Issue by ssette** [grijjy/GrijjyFoundation#4]
I'm unable to serialize TDateTime member. The deserialization works fine i.e if I try to deserialize a value like this one  "createTime": "2017-09-05T15:58:39.286+02:00" create a correct DateTime value.

But, when I try to serialize a TDateTime member then the result is something like this : {createDate":{"$date" : 150465600000}}
I'm doing something wrongs ?

**Comment by ssette** [comment]
Sorry, just released i need to annotate my TDateTime member with [BsonRepresentation(TgoBsonRepresentation.String)]

**Comment by erikvanbilsen** [comment]
That's correct. By default, TDateTime values are serialized as 64-integer values containing the number of milliseconds that have passed since the Unix epoch. That is a bit more efficient in terms of storage size and computation.
