### ISSUE TITLE
Does support Grijjy.Collections unit for the older than delphiXE7?

### ISSUE THREAD

**Issue by kuksundo** [grijjy/GrijjyFoundation#41]
Hi,

In Grijjy.Collections Unit, IsTypeManaged() function is used.
But this function is only for newer delphiXE7.

Your GrijjyFoundation is support only for newer XE7?
Or is any option to use GrijjyFoundation unit in older XE5?

**Comment by grijjy** [comment]
We don't support old(er) Delphi versions for our open source projects. We are not a component vendor and we only use and test on the latest Delphi versions (10.4 and 11). So we cannot guarantee that our code will compile on other versions.
