### ISSUE TITLE
D12 Athens gives compiler hint(s)

### ISSUE THREAD

**Issue by TommiPrami** [grijjy/GrijjyFoundation#54]
[dcc32 Hint] Grijjy.Collections.pas(909): H2077 Value assigned to 'TgoReadOnlySet<T>.Contains' never used

and

[dcc32 Hint] Grijjy.Collections.pas(1807): H2077 Value assigned to 'TgoValueDictionary<TKey,TValue>.ContainsKey' never used

Propose changing them into:

function TgoReadOnlySet<T>.Contains(const AItem: T): Boolean;
var
  Mask, Index, HashCode, HC: Integer;
begin
  Result := False;

  if FCount = 0 then
    Exit;

  HashCode := FComparer.GetHashCode(AItem) and $7FFFFFFF;
  Mask := Length(FItems) - 1;
  Index := HashCode and Mask;

  while True do
  begin
    HC := FItems[Index].HashCode;
    if (HC = EMPTY_HASH) then
      Exit(False);

    if (HC = HashCode) and FComparer.Equals(FItems[Index].Item, AItem) then
      Exit(True);

    Index := (Index + 1) and Mask;
  end;
end;

and

function TgoValueDictionary<TKey, TValue>.ContainsKey(
  const AKey: TKey): Boolean;
var
  Mask, Index, HashCode, HC: Integer;
begin
  Result := False;

  if FCount = 0 then
    Exit;

  HashCode := FComparer.GetHashCode(AKey) and $7FFFFFFF;
  Mask := Length(FItems) - 1;
  Index := HashCode and Mask;

  while True do
  begin
    HC := FItems[Index].HashCode;
    if (HC = EMPTY_HASH) then
      Exit(False);

    if (HC = HashCode) and FComparer.Equals(FItems[Index].Key, AKey) then
      Exit(True);

    Index := (Index + 1) and Mask;
  end;
end;

-Tee-

**Comment by erikvanbilsen** [comment]
I implemented your suggested changes, but since I haven't installed Delphi 12 yet, I cannot confirm if this removes the hints.

**Comment by TommiPrami** [comment]
It removes them in D12
