### ISSUE TITLE
JSON unit tests failing because default format settings are used

### ISSUE THREAD

**Issue by jpluimers** [grijjy/GrijjyFoundation#6]
The JSON reading uses US format settings, but writing uses the default.

This for instance fails on systems having a decimal comma.

**Comment by erikvanbilsen** [comment]
Thanks for reporting this issue and fixing it!
I would have noticed this issue myself if I still lived in The Netherlands ;)

**Comment by jpluimers** [comment]
No problem, and I know ;) that opportunity for working/moving abroad closed for me when I - too suddenly - became curator of my mentally retarded brother some 15 years ago.

Living in AMS close to EHAM, let me know if you ever get there. Grab some coffee (:

BTW: The people at the current git wonder how to pronounce grijjy: https://twitter.com/jpluimers/status/1055470263184384001
