### ISSUE TITLE
Deserialize Memory Leak

### ISSUE THREAD

**Issue by chmichael** [grijjy/GrijjyFoundation#8]
Hello,
  Attached a sample project!

[Deserialize.Memory.Leak.zip](https://github.com/grijjy/GrijjyFoundation/files/2548624/Deserialize.Memory.Leak.zip)

**Comment by erikvanbilsen** [comment]
Thanks for reporting!
Issue should be fixed now.

**Comment by chmichael** [comment]
Thank you :)

**Comment by jpluimers** [comment]
Sorry: that commit was meant for #12.
